"""Recreate all tables

Revision ID: 1140461c8ccb
Revises: 
Create Date: 2025-06-05 09:01:17.717927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1140461c8ccb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_contexts', 'prompt_used')
    op.drop_column('invoice_contexts', 'ocr_text')
    op.drop_column('invoice_contexts', 'llm_response_raw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_contexts', sa.Column('llm_response_raw', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoice_contexts', sa.Column('ocr_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('invoice_contexts', sa.Column('prompt_used', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
