"""Add MessageHistory table

Revision ID: 3cd2ad219ddb
Revises: aa4d1590bd69
Create Date: 2025-06-05 12:08:47.707116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd2ad219ddb'
down_revision: Union[str, None] = 'aa4d1590bd69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('message_history_invoice_id_fkey'), 'message_history', type_='foreignkey')
    op.create_foreign_key(None, 'message_history', 'client_contexts', ['client_id'], ['client_id'])
    op.drop_column('message_history', 'invoice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message_history', sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message_history', type_='foreignkey')
    op.create_foreign_key(op.f('message_history_invoice_id_fkey'), 'message_history', 'invoice_contexts', ['invoice_id'], ['id'])
    # ### end Alembic commands ###
