"""Add MCP fields to invoice_contexts

Revision ID: aa4d1590bd69
Revises: 1140461c8ccb
Create Date: 2025-06-05 09:18:01.116662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa4d1590bd69'
down_revision: Union[str, None] = '1140461c8ccb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_contexts', sa.Column('ocr_text', sa.Text(), nullable=True))
    op.add_column('invoice_contexts', sa.Column('prompt_used', sa.Text(), nullable=True))
    op.add_column('invoice_contexts', sa.Column('llm_response_raw', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_contexts', 'llm_response_raw')
    op.drop_column('invoice_contexts', 'prompt_used')
    op.drop_column('invoice_contexts', 'ocr_text')
    # ### end Alembic commands ###
